%% main script with parameters
clear all;
close all;
clc;

%% define the positions of the sensors
basestation_positions = [7.5, 3.5;   ...
                     13, 6;      ...
                     20, 3.5;    ...
                     22, 7.5;    ...
                     7.5, 7.5;   ...
                     10, 10;     ...
                     10, 1;      ...
                     17.5, 10;   ...
                     17.5, 2;    ...
                    ];

beacons_radius = 7;
sampling_time = 1;    % distance between each "polling cycle"
var_z = 0.1;


%name_trajectory = 'easy2.mat';
name_trajectory = 'hard2.mat';

polling_delay = round(400/25);

% set of coefficients which defines the model of the device that perform measurements
rssi_model_coeff = [-0.1416, 2.311, -14.76, 36.79];

[prediction, dist_err, dist_max, RMSE_x, RMSE_y, RMSE_net] = ekf_tracking_polling(name_trajectory, ...
                                                                             basestation_positions, ...
                                                                             beacons_radius, ...
                                                                             sampling_time, ...
                                                                             polling_delay, ...
                                                                             var_z, ...
                                                                             rssi_model_coeff ...
                                                                            );

disp(['Distance Error  Avg: ',num2str(dist_err)]);
disp(['Distance Error Max : ',num2str(dist_max)]);
disp(['RMSE_x : ',num2str(RMSE_x)]);
disp(['RMSE_y : ',num2str(RMSE_y)]);
disp(['RMSE_net : ',num2str(RMSE_net)]);

plot(prediction(:,1),prediction(:,2),'Color','Red');

xlabel('x coordinate [m]');
ylabel('y coordinate [m]');    